
import Model.Model;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Vector;
import static java.util.stream.Collectors.toList;
import static java.util.stream.Collectors.toMap;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class CardsTemplatesDialog2 extends javax.swing.JDialog {

    Model.Deck deck;
            
    /**
     * Creates new form FCCardTemplatesDialog
     */
    
    public CardsTemplatesDialog2(java.awt.Dialog parent, Model.Deck deck) {
        super(parent, true);
        
        this.deck = deck;
        
        initComponents();
        
        
        Misc.centerWindow(this);        

        Misc.assignESCforClose(this);
        getRootPane().setDefaultButton(jButtonExit);
        
        if (deck.listTemplates().size() == 0) {
            // create default template
            deck.createTemplate("<default>");
        }

        rebuildTemplateList();
        rebuildTables();
    }

    void rebuildTemplateList() {
        List<Model.Deck.Template> templates = deck.listTemplates();
        DefaultComboBoxModel<Model.Deck.Template> m = (DefaultComboBoxModel) jComboBoxTemplates.getModel();
        m.removeAllElements();
//        templates.forEach(t->m.addElement(new JComboBoxTemplatesItem (t.getID(), t.getName())));
        templates.forEach(t->m.addElement(t));
    }
    
    void rebuildTables() {
        Model.Deck.Template t = (Model.Deck.Template) jComboBoxTemplates.getSelectedItem();
        
        List<Model.Deck.Field> fields = deck.listVisibleFields();

        for (boolean i: new boolean[] {true, false}) {
            JTable jtable = i?jTableFront:jTableBack;
            DefaultTableModel model = (DefaultTableModel) jtable.getModel();
            model.setRowCount(0);
            
            if (t != null) fields.stream()
                .sorted((f1,f2)->(Integer.compare(t.getTemplateField(i, f1.getName()).order, t.getTemplateField(i, f2.getName()).order)))
                .forEachOrdered(f -> {
                    Model.CardTemplateField tf = t.getTemplateField(i, f.getName());
                    String[] row = new String[5];
                    row[0] = f.getName();
                    row[1] = tf.action;
                    row[2] = tf.fontSize;
                    row[3] = tf.color;
                    row[4] = tf.prompt;
                    model.addRow(row);
                });
        }
    }
    
    void applyChanges(Model.Deck.Template t){
//        FCModel.FCDeck.FCCardTemplate t = (FCModel.FCDeck.FCCardTemplate) jComboBoxTemplates.getSelectedItem();

        if (t!=null) for (boolean i: new boolean[] {true, false}) {
            JTable jtable = i?jTableFront:jTableBack;
            DefaultTableModel model = (DefaultTableModel) jtable.getModel();
/*            
            model.getDataVector().forEach( rr -> {
                Vector r = (Vector)rr;
                FCModel.FCCardTemplateField tf = new FCModel.FCCardTemplateField();
                tf.action = (String) r.elementAt(1);
                tf.fontSize = (String) r.elementAt(2);
                tf.color = (String) r.elementAt(3);
                tf.prompt = (String) r.elementAt(4);
                t.putTemplateField(i, (String) r.elementAt(0), tf);
            });
*/
            for (int j=0; j<model.getRowCount(); j++){
                Model.CardTemplateField tf = new Model.CardTemplateField();

                tf.action = (String) model.getValueAt(j, 1);
                tf.fontSize = (String) model.getValueAt(j, 2);
                tf.color = (String) model.getValueAt(j, 3);
                tf.prompt = (String) model.getValueAt(j, 4);
                tf.order=j;
                
                t.putTemplateField(i, (String) model.getValueAt(j, 0), tf);
                
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxTableAction = new javax.swing.JComboBox();
        jComboBoxTableFontSize = new javax.swing.JComboBox();
        jComboBoxTableColor = new javax.swing.JComboBox();
        jComboBoxTableAction1 = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jButtonAddTemplate = new javax.swing.JButton();
        jComboBoxTemplates = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jButtonRenameTemplate = new javax.swing.JButton();
        jButtonDeleteTemplate = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButtonExit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButtonPreviewFront = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFront = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableBack = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButtonPreviewBack = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jComboBoxTableAction.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hide", "Text", "Type", "Image", "Sound" }));

        jComboBoxTableFontSize.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "10", "15", "20", "30", "40", "60" }));

        jComboBoxTableColor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Black", "Gray", "Red", "Green", "Blue", "Yellow", "Cyan", "Magenta" }));

        jComboBoxTableAction1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hide", "Text", "Compare", "Image", "Sound" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cards Templates");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                onWindowClosing(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonAddTemplate.setText("+");
        jButtonAddTemplate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddTemplateActionPerformed(evt);
            }
        });

        jComboBoxTemplates.setModel(new javax.swing.DefaultComboBoxModel<>( ));
        jComboBoxTemplates.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                onItemStateChange(evt);
            }
        });
        jComboBoxTemplates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTemplatesActionPerformed(evt);
            }
        });

        jLabel1.setText("Templates:");

        jButtonRenameTemplate.setText("Rename...");
        jButtonRenameTemplate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRenameTemplateActionPerformed(evt);
            }
        });

        jButtonDeleteTemplate.setText("-");
        jButtonDeleteTemplate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteTemplateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxTemplates, 0, 330, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAddTemplate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDeleteTemplate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRenameTemplate)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxTemplates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddTemplate)
                    .addComponent(jButtonDeleteTemplate)
                    .addComponent(jButtonRenameTemplate)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonExit)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Front of the Card (Question):");

        jButton1.setText("\u2191");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("\u2193");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButtonPreviewFront.setText("Preview");
        jButtonPreviewFront.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPreviewFrontActionPerformed(evt);
            }
        });

        jTableFront.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Field", "What to do", "Font size", "Color", "Prompt"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableFront);
        if (jTableFront.getColumnModel().getColumnCount() > 0) {
            jTableFront.getColumnModel().getColumn(1).setCellEditor(new DefaultCellEditor(jComboBoxTableAction));
            jTableFront.getColumnModel().getColumn(2).setCellEditor(new DefaultCellEditor(jComboBoxTableFontSize));
            jTableFront.getColumnModel().getColumn(3).setCellEditor(new DefaultCellEditor(jComboBoxTableColor));
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPreviewFront, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButtonPreviewFront))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton3.setText("\u2191");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTableBack.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Field", "What to do", "Font size", "Color", "Prompt"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableBack);
        if (jTableBack.getColumnModel().getColumnCount() > 0) {
            jTableBack.getColumnModel().getColumn(1).setCellEditor(new DefaultCellEditor(jComboBoxTableAction1));
            jTableBack.getColumnModel().getColumn(2).setCellEditor(new DefaultCellEditor(jComboBoxTableFontSize));
            jTableBack.getColumnModel().getColumn(3).setCellEditor(new DefaultCellEditor(jComboBoxTableColor));
        }

        jButton4.setText("\u2193");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButtonPreviewBack.setText("Preview");
        jButtonPreviewBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPreviewBackActionPerformed(evt);
            }
        });

        jLabel3.setText("Back of the Card (Answer):");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonPreviewBack, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButtonPreviewBack))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddTemplateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddTemplateActionPerformed
        String s = JOptionPane.showInputDialog("Please input template name");
        if ((s != null) && (s.length()>0)) {
            Model.Deck.Template t = deck.createTemplate(s);
            rebuildTemplateList();
            jComboBoxTemplates.setSelectedItem(t);
        }
    }//GEN-LAST:event_jButtonAddTemplateActionPerformed

    private void jComboBoxTemplatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTemplatesActionPerformed
        rebuildTables();
    }//GEN-LAST:event_jComboBoxTemplatesActionPerformed

    private void onWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_onWindowClosing
        Model.Deck.Template template = (Model.Deck.Template) jComboBoxTemplates.getSelectedItem();
        if (template!=null) applyChanges(template);
    }//GEN-LAST:event_onWindowClosing

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        Misc.closeWindow(this);
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void onItemStateChange(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_onItemStateChange
        if (evt.getStateChange()==ItemEvent.DESELECTED) {
            applyChanges((Model.Deck.Template) evt.getItem());
        }
    }//GEN-LAST:event_onItemStateChange

    void previewTemplate(boolean isFront) {
        Model.Deck.Template template = (Model.Deck.Template) jComboBoxTemplates.getSelectedItem();
        if (template==null) return;
        applyChanges(template);
        
        new ShowCardDialog(this, template, isFront).setVisible(true);        
    }
    private void jButtonPreviewFrontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPreviewFrontActionPerformed
        previewTemplate(true);
    }//GEN-LAST:event_jButtonPreviewFrontActionPerformed

    private void jButtonPreviewBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPreviewBackActionPerformed
        previewTemplate(false);
    }//GEN-LAST:event_jButtonPreviewBackActionPerformed

    private void jButtonDeleteTemplateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteTemplateActionPerformed
        Model.Deck.Template t = (Model.Deck.Template) jComboBoxTemplates.getSelectedItem();
        if (t!=null) {
            DefaultComboBoxModel<Model.Deck.Template> m = (DefaultComboBoxModel) jComboBoxTemplates.getModel();
            m.removeElement(t);
            deck.deleteTemplate(t);
        }
    }//GEN-LAST:event_jButtonDeleteTemplateActionPerformed

    private void jButtonRenameTemplateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRenameTemplateActionPerformed
        Model.Deck.Template t = (Model.Deck.Template) jComboBoxTemplates.getSelectedItem();
        if (t!=null) {
            String s = JOptionPane.showInputDialog("Please input template name", t.toString());
            if ((s != null) && (s.length()>0)) {
                t.setName(s);
                rebuildTemplateList();
                jComboBoxTemplates.setSelectedItem(t);
            }            
        }

    }//GEN-LAST:event_jButtonRenameTemplateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTableFront.getModel();
        int sr = jTableFront.getSelectedRow();
        if (sr>0) {
            model.moveRow(sr, sr, sr-1);
            jTableFront.setRowSelectionInterval(sr-1, sr-1);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTableFront.getModel();
        int sr = jTableFront.getSelectedRow();
        if (sr<model.getRowCount()-1) {
            model.moveRow(sr, sr, sr+1);
            jTableFront.setRowSelectionInterval(sr+1, sr+1);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTableBack.getModel();
        int sr = jTableBack.getSelectedRow();
        if (sr>0) {
            model.moveRow(sr, sr, sr-1);
            jTableBack.setRowSelectionInterval(sr-1, sr-1);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTableBack.getModel();
        int sr = jTableBack.getSelectedRow();
        if (sr<model.getRowCount()-1) {
            model.moveRow(sr, sr, sr+1);
            jTableBack.setRowSelectionInterval(sr+1, sr+1);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonAddTemplate;
    private javax.swing.JButton jButtonDeleteTemplate;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonPreviewBack;
    private javax.swing.JButton jButtonPreviewFront;
    private javax.swing.JButton jButtonRenameTemplate;
    private javax.swing.JComboBox jComboBoxTableAction;
    private javax.swing.JComboBox jComboBoxTableAction1;
    private javax.swing.JComboBox jComboBoxTableColor;
    private javax.swing.JComboBox jComboBoxTableFontSize;
    private javax.swing.JComboBox jComboBoxTemplates;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableBack;
    private javax.swing.JTable jTableFront;
    // End of variables declaration//GEN-END:variables
}
