
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.KeyStroke;
import Model.*;
import java.awt.Component;
import java.awt.Font;
import java.io.IOException;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JList;
import static javax.swing.JOptionPane.WARNING_MESSAGE;
import static javax.swing.JOptionPane.showInputDialog;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.ListCellRenderer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class CustomStacksDialog extends javax.swing.JDialog {

    Model.Deck.LearningSession ls;
    Model.Deck.LearningSession.Stack result = null;
    
    public CustomStacksDialog(JDialog parent, Model.Deck.LearningSession ls) {
        super(parent, true);
        this.ls = ls;
        
        initComponents();

        
        Misc.centerWindow(this);        

        Misc.assignESCforClose(this);
        
        class DefCellRenderer extends DefaultListCellRenderer {
            @Override
            public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                Model.Deck.LearningSession.Stack stack = (Model.Deck.LearningSession.Stack) value;
                String s = "";
                
                s+=stack.getName();
                s+=" ["+Integer.toString(stack.getVisibleCardsNumber())+" cards]";
                setText(s);

                if (stack.isCustom()) setFont(new Font(getFont().getFontName(), Font.ITALIC, getFont().getSize()));                
                
                return this;
            }
        };

        jListStacks.setCellRenderer(new DefCellRenderer());

        rebuildStackList();
    }
    
    void rebuildStackList() {
        DefaultListModel lm = (DefaultListModel)jListStacks.getModel();
        lm.clear();
        ls.listStacks().forEach(s->lm.addElement(s));
    }
    
    Model.Deck.LearningSession.Stack showDialog() {
        setVisible(true);
        return result;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonDeleteStack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListStacks = new javax.swing.JList();
        jButtonAddStack = new javax.swing.JButton();
        jButtonRenameStack = new javax.swing.JButton();
        jButtonOk = new javax.swing.JButton();
        jButtonShow = new javax.swing.JButton();
        jButtonLearn = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Stacks");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonDeleteStack.setText("-");
        jButtonDeleteStack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteStackActionPerformed(evt);
            }
        });

        jListStacks.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(jListStacks);

        jButtonAddStack.setText("+");
        jButtonAddStack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddStackActionPerformed(evt);
            }
        });

        jButtonRenameStack.setText("Rename...");
        jButtonRenameStack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRenameStackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonAddStack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDeleteStack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonRenameStack)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddStack)
                    .addComponent(jButtonDeleteStack)
                    .addComponent(jButtonRenameStack))
                .addContainerGap())
        );

        jButtonOk.setText("Ok");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });

        jButtonShow.setText("Show...");

        jButtonLearn.setText("Learn...");
        jButtonLearn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLearnActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonOk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonShow, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(jButtonLearn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonOk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonShow)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonLearn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddStackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddStackActionPerformed
        String s = showInputDialog("Please input New Stack name");
        if ((s != null) && (s.length()>0)) {
            try {
                ((DefaultListModel)jListStacks.getModel()).addElement(ls.createStack(s, true));
            } catch (Model.Exception ex) {
                showMessageDialog(this, ex.getMessage(), "Error", WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButtonAddStackActionPerformed

    private void jButtonDeleteStackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteStackActionPerformed
        Model.Deck.LearningSession.Stack stack = (Model.Deck.LearningSession.Stack)jListStacks.getSelectedValue();

        if (stack!=null) {
            if (!stack.isCustom()){
                showMessageDialog(this, "Can not delete built-it stack", "Error", WARNING_MESSAGE);
            } else if (stack.getCardsNumber()>0){
                showMessageDialog(this, "Stack is not empty", "Error", WARNING_MESSAGE);
            } else {
                ((DefaultListModel)jListStacks.getModel()).removeElement(stack);
                ls.deleteStack(stack);
            }
        }
        
    }//GEN-LAST:event_jButtonDeleteStackActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        ls.getDeck().dbCommit();
    }//GEN-LAST:event_formWindowClosing

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        result = (Model.Deck.LearningSession.Stack)jListStacks.getSelectedValue();
        Misc.closeWindow(this);
    }//GEN-LAST:event_jButtonOkActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        Misc.closeWindow(this);
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonLearnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLearnActionPerformed
        Model.Deck.LearningSession.Stack stack = (Model.Deck.LearningSession.Stack)jListStacks.getSelectedValue();
        if (stack!=null && stack.getVisibleCardsNumber()>0) {
            new ShowCardDialog(this, stack, null).setVisible(true);
            rebuildStackList();
        }
    }//GEN-LAST:event_jButtonLearnActionPerformed

    private void jButtonRenameStackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRenameStackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRenameStackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddStack;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonDeleteStack;
    private javax.swing.JButton jButtonLearn;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JButton jButtonRenameStack;
    private javax.swing.JButton jButtonShow;
    private javax.swing.JList jListStacks;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
